// This file is part of caniuse-serde. It is subject to the license terms in the COPYRIGHT file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/caniuse-serde/master/COPYRIGHT. No part of predicator, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the COPYRIGHT file.
// Copyright © 2017 The developers of caniuse-serde. See the COPYRIGHT file in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/caniuse-serde/master/COPYRIGHT.


/// A helper enum to make it easier to use regional usage references in data structures that are serialized or deserialized with Serde
/// The two-letter codes are ISO 3166 country codes.
#[allow(missing_docs)]
#[derive(Deserialize, Serialize, Debug, Copy, Clone, Ord, PartialOrd, Eq, PartialEq, Hash)]
pub enum RegionalUsages
{
	/// World-wide usage
	#[serde(rename = "alt-ww")] WorldWide,
	
	/// Usage in Africa
	#[serde(rename = "alt-af")] Africa,
	
	/// Usage in Antarctica
	#[serde(rename = "alt-an")] Antarctica,
	
	/// Usage in Asia
	#[serde(rename = "alt-as")] Asia,
	
	/// Usage in Europe
	#[serde(rename = "alt-eu")] Europe,
	
	/// Usage in North America
	#[serde(rename = "alt-na")] NorthAmerica,
	
	/// Usage in Oceania
	#[serde(rename = "alt-oc")] Oceania,
	
	/// Usage in South America
	#[serde(rename = "alt-sa")] SouthAmerica,
	
	AD,
	AE,
	AF,
	AG,
	AI,
	AL,
	AM,
	AN,
	AO,
	AR,
	AS,
	AT,
	AU,
	AW,
	AX,
	AZ,
	BA,
	BB,
	BD,
	BE,
	BF,
	BG,
	BH,
	BI,
	BJ,
	BM,
	BN,
	BO,
	BR,
	BS,
	BT,
	BW,
	BY,
	BZ,
	CA,
	CD,
	CF,
	CG,
	CH,
	CI,
	CK,
	CL,
	CM,
	CN,
	CO,
	CR,
	CU,
	CV,
	CX,
	CY,
	CZ,
	DE,
	DJ,
	DK,
	DM,
	DO,
	DZ,
	EC,
	EE,
	EG,
	ER,
	ES,
	ET,
	FI,
	FJ,
	FK,
	FM,
	FO,
	FR,
	GA,
	GB,
	GD,
	GE,
	GF,
	GG,
	GH,
	GI,
	GL,
	GM,
	GN,
	GP,
	GQ,
	GR,
	GT,
	GU,
	GW,
	GY,
	HK,
	HN,
	HR,
	HT,
	HU,
	ID,
	IE,
	IL,
	IM,
	IN,
	IQ,
	IR,
	IS,
	IT,
	JE,
	JM,
	JO,
	JP,
	KE,
	KG,
	KH,
	KI,
	KM,
	KN,
	KP,
	KR,
	KW,
	KY,
	KZ,
	LA,
	LB,
	LC,
	LI,
	LK,
	LR,
	LS,
	LT,
	LU,
	LV,
	LY,
	MA,
	MC,
	MD,
	ME,
	MG,
	MH,
	MK,
	ML,
	MM,
	MN,
	MO,
	MP,
	MQ,
	MR,
	MS,
	MT,
	MU,
	MV,
	MW,
	MX,
	MY,
	MZ,
	NA,
	NC,
	NE,
	NF,
	NG,
	NI,
	NL,
	NO,
	NP,
	NR,
	NU,
	NZ,
	OM,
	PA,
	PE,
	PF,
	PG,
	PH,
	PK,
	PL,
	PM,
	PN,
	PR,
	PS,
	PT,
	PW,
	PY,
	QA,
	RE,
	RO,
	RS,
	RU,
	RW,
	SA,
	SB,
	SC,
	SD,
	SE,
	SG,
	SH,
	SI,
	SK,
	SL,
	SM,
	SN,
	SO,
	SR,
	ST,
	SV,
	SY,
	SZ,
	TC,
	TD,
	TG,
	TH,
	TJ,
	TK,
	TL,
	TM,
	TN,
	TO,
	TR,
	TT,
	TV,
	TW,
	TZ,
	UA,
	UG,
	US,
	UY,
	UZ,
	VA,
	VC,
	VE,
	VG,
	VI,
	VN,
	VU,
	WF,
	WS,
	YE,
	YT,
	ZA,
	ZM,
	ZW,
}

impl Default for RegionalUsages
{
	#[inline(always)]
	fn default() -> Self
	{
		RegionalUsages::WorldWide
	}
}

impl FromStr for RegionalUsages
{
	type Err = RegionalUsagesFromStrError;
	
	#[inline(always)]
	fn from_str(can_i_use_iso_like_code: &str) -> Result<Self, Self::Err>
	{
		use self::RegionalUsages::*;
		
		match can_i_use_iso_like_code
		{
			"alt-ww" => Ok(WorldWide),
			
			"alt-af" => Ok(Africa),
			"alt-an" => Ok(Antarctica),
			"alt-as" => Ok(Asia),
			"alt-eu" => Ok(Europe),
			"alt-na" => Ok(NorthAmerica),
			"alt-oc" => Ok(Oceania),
			"alt-sa" => Ok(SouthAmerica),
			
			"AD" => Ok(AD),
			"AE" => Ok(AE),
			"AF" => Ok(AF),
			"AG" => Ok(AG),
			"AI" => Ok(AI),
			"AL" => Ok(AL),
			"AM" => Ok(AM),
			"AN" => Ok(AN),
			"AO" => Ok(AO),
			"AR" => Ok(AR),
			"AS" => Ok(AS),
			"AT" => Ok(AT),
			"AU" => Ok(AU),
			"AW" => Ok(AW),
			"AX" => Ok(AX),
			"AZ" => Ok(AZ),
			"BA" => Ok(BA),
			"BB" => Ok(BB),
			"BD" => Ok(BD),
			"BE" => Ok(BE),
			"BF" => Ok(BF),
			"BG" => Ok(BG),
			"BH" => Ok(BH),
			"BI" => Ok(BI),
			"BJ" => Ok(BJ),
			"BM" => Ok(BM),
			"BN" => Ok(BN),
			"BO" => Ok(BO),
			"BR" => Ok(BR),
			"BS" => Ok(BS),
			"BT" => Ok(BT),
			"BW" => Ok(BW),
			"BY" => Ok(BY),
			"BZ" => Ok(BZ),
			"CA" => Ok(CA),
			"CD" => Ok(CD),
			"CF" => Ok(CF),
			"CG" => Ok(CG),
			"CH" => Ok(CH),
			"CI" => Ok(CI),
			"CK" => Ok(CK),
			"CL" => Ok(CL),
			"CM" => Ok(CM),
			"CN" => Ok(CN),
			"CO" => Ok(CO),
			"CR" => Ok(CR),
			"CU" => Ok(CU),
			"CV" => Ok(CV),
			"CX" => Ok(CX),
			"CY" => Ok(CY),
			"CZ" => Ok(CZ),
			"DE" => Ok(DE),
			"DJ" => Ok(DJ),
			"DK" => Ok(DK),
			"DM" => Ok(DM),
			"DO" => Ok(DO),
			"DZ" => Ok(DZ),
			"EC" => Ok(EC),
			"EE" => Ok(EE),
			"EG" => Ok(EG),
			"ER" => Ok(ER),
			"ES" => Ok(ES),
			"ET" => Ok(ET),
			"FI" => Ok(FI),
			"FJ" => Ok(FJ),
			"FK" => Ok(FK),
			"FM" => Ok(FM),
			"FO" => Ok(FO),
			"FR" => Ok(FR),
			"GA" => Ok(GA),
			"GB" => Ok(GB),
			"GD" => Ok(GD),
			"GE" => Ok(GE),
			"GF" => Ok(GF),
			"GG" => Ok(GG),
			"GH" => Ok(GH),
			"GI" => Ok(GI),
			"GL" => Ok(GL),
			"GM" => Ok(GM),
			"GN" => Ok(GN),
			"GP" => Ok(GP),
			"GQ" => Ok(GQ),
			"GR" => Ok(GR),
			"GT" => Ok(GT),
			"GU" => Ok(GU),
			"GW" => Ok(GW),
			"GY" => Ok(GY),
			"HK" => Ok(HK),
			"HN" => Ok(HN),
			"HR" => Ok(HR),
			"HT" => Ok(HT),
			"HU" => Ok(HU),
			"ID" => Ok(ID),
			"IE" => Ok(IE),
			"IL" => Ok(IL),
			"IM" => Ok(IM),
			"IN" => Ok(IN),
			"IQ" => Ok(IQ),
			"IR" => Ok(IR),
			"IS" => Ok(IS),
			"IT" => Ok(IT),
			"JE" => Ok(JE),
			"JM" => Ok(JM),
			"JO" => Ok(JO),
			"JP" => Ok(JP),
			"KE" => Ok(KE),
			"KG" => Ok(KG),
			"KH" => Ok(KH),
			"KI" => Ok(KI),
			"KM" => Ok(KM),
			"KN" => Ok(KN),
			"KP" => Ok(KP),
			"KR" => Ok(KR),
			"KW" => Ok(KW),
			"KY" => Ok(KY),
			"KZ" => Ok(KZ),
			"LA" => Ok(LA),
			"LB" => Ok(LB),
			"LC" => Ok(LC),
			"LI" => Ok(LI),
			"LK" => Ok(LK),
			"LR" => Ok(LR),
			"LS" => Ok(LS),
			"LT" => Ok(LT),
			"LU" => Ok(LU),
			"LV" => Ok(LV),
			"LY" => Ok(LY),
			"MA" => Ok(MA),
			"MC" => Ok(MC),
			"MD" => Ok(MD),
			"ME" => Ok(ME),
			"MG" => Ok(MG),
			"MH" => Ok(MH),
			"MK" => Ok(MK),
			"ML" => Ok(ML),
			"MM" => Ok(MM),
			"MN" => Ok(MN),
			"MO" => Ok(MO),
			"MP" => Ok(MP),
			"MQ" => Ok(MQ),
			"MR" => Ok(MR),
			"MS" => Ok(MS),
			"MT" => Ok(MT),
			"MU" => Ok(MU),
			"MV" => Ok(MV),
			"MW" => Ok(MW),
			"MX" => Ok(MX),
			"MY" => Ok(MY),
			"MZ" => Ok(MZ),
			"NA" => Ok(NA),
			"NC" => Ok(NC),
			"NE" => Ok(NE),
			"NF" => Ok(NF),
			"NG" => Ok(NG),
			"NI" => Ok(NI),
			"NL" => Ok(NL),
			"NO" => Ok(NO),
			"NP" => Ok(NP),
			"NR" => Ok(NR),
			"NU" => Ok(NU),
			"NZ" => Ok(NZ),
			"OM" => Ok(OM),
			"PA" => Ok(PA),
			"PE" => Ok(PE),
			"PF" => Ok(PF),
			"PG" => Ok(PG),
			"PH" => Ok(PH),
			"PK" => Ok(PK),
			"PL" => Ok(PL),
			"PM" => Ok(PM),
			"PN" => Ok(PN),
			"PR" => Ok(PR),
			"PS" => Ok(PS),
			"PT" => Ok(PT),
			"PW" => Ok(PW),
			"PY" => Ok(PY),
			"QA" => Ok(QA),
			"RE" => Ok(RE),
			"RO" => Ok(RO),
			"RS" => Ok(RS),
			"RU" => Ok(RU),
			"RW" => Ok(RW),
			"SA" => Ok(SA),
			"SB" => Ok(SB),
			"SC" => Ok(SC),
			"SD" => Ok(SD),
			"SE" => Ok(SE),
			"SG" => Ok(SG),
			"SH" => Ok(SH),
			"SI" => Ok(SI),
			"SK" => Ok(SK),
			"SL" => Ok(SL),
			"SM" => Ok(SM),
			"SN" => Ok(SN),
			"SO" => Ok(SO),
			"SR" => Ok(SR),
			"ST" => Ok(ST),
			"SV" => Ok(SV),
			"SY" => Ok(SY),
			"SZ" => Ok(SZ),
			"TC" => Ok(TC),
			"TD" => Ok(TD),
			"TG" => Ok(TG),
			"TH" => Ok(TH),
			"TJ" => Ok(TJ),
			"TK" => Ok(TK),
			"TL" => Ok(TL),
			"TM" => Ok(TM),
			"TN" => Ok(TN),
			"TO" => Ok(TO),
			"TR" => Ok(TR),
			"TT" => Ok(TT),
			"TV" => Ok(TV),
			"TW" => Ok(TW),
			"TZ" => Ok(TZ),
			"UA" => Ok(UA),
			"UG" => Ok(UG),
			"US" => Ok(US),
			"UY" => Ok(UY),
			"UZ" => Ok(UZ),
			"VA" => Ok(VA),
			"VC" => Ok(VC),
			"VE" => Ok(VE),
			"VG" => Ok(VG),
			"VI" => Ok(VI),
			"VN" => Ok(VN),
			"VU" => Ok(VU),
			"WF" => Ok(WF),
			"WS" => Ok(WS),
			"YE" => Ok(YE),
			"YT" => Ok(YT),
			"ZA" => Ok(ZA),
			"ZM" => Ok(ZM),
			"ZW" => Ok(ZW),
			
			_ => Err(RegionalUsagesFromStrError)
		}
	}
}

impl RegionalUsages
{
	/// Returns a reference to an embedded regional usage database
	#[inline(always)]
	pub fn regional_usage(&self) -> &'static RegionalUsage
	{
		use self::RegionalUsages::*;
		
		match *self
		{
			WorldWide => &::regional_usage::WorldWide,
			
			Africa => &::regional_usage::Africa,
			Antarctica => &::regional_usage::Antarctica,
			Asia => &::regional_usage::Asia,
			Europe => &::regional_usage::Europe,
			NorthAmerica => &::regional_usage::NorthAmerica,
			Oceania => &::regional_usage::Oceania,
			SouthAmerica => &::regional_usage::SouthAmerica,
			
			AD => &::regional_usage::AD,
			AE => &::regional_usage::AE,
			AF => &::regional_usage::AF,
			AG => &::regional_usage::AG,
			AI => &::regional_usage::AI,
			AL => &::regional_usage::AL,
			AM => &::regional_usage::AM,
			AN => &::regional_usage::AN,
			AO => &::regional_usage::AO,
			AR => &::regional_usage::AR,
			AS => &::regional_usage::AS,
			AT => &::regional_usage::AT,
			AU => &::regional_usage::AU,
			AW => &::regional_usage::AW,
			AX => &::regional_usage::AX,
			AZ => &::regional_usage::AZ,
			BA => &::regional_usage::BA,
			BB => &::regional_usage::BB,
			BD => &::regional_usage::BD,
			BE => &::regional_usage::BE,
			BF => &::regional_usage::BF,
			BG => &::regional_usage::BG,
			BH => &::regional_usage::BH,
			BI => &::regional_usage::BI,
			BJ => &::regional_usage::BJ,
			BM => &::regional_usage::BM,
			BN => &::regional_usage::BN,
			BO => &::regional_usage::BO,
			BR => &::regional_usage::BR,
			BS => &::regional_usage::BS,
			BT => &::regional_usage::BT,
			BW => &::regional_usage::BW,
			BY => &::regional_usage::BY,
			BZ => &::regional_usage::BZ,
			CA => &::regional_usage::CA,
			CD => &::regional_usage::CD,
			CF => &::regional_usage::CF,
			CG => &::regional_usage::CG,
			CH => &::regional_usage::CH,
			CI => &::regional_usage::CI,
			CK => &::regional_usage::CK,
			CL => &::regional_usage::CL,
			CM => &::regional_usage::CM,
			CN => &::regional_usage::CN,
			CO => &::regional_usage::CO,
			CR => &::regional_usage::CR,
			CU => &::regional_usage::CU,
			CV => &::regional_usage::CV,
			CX => &::regional_usage::CX,
			CY => &::regional_usage::CY,
			CZ => &::regional_usage::CZ,
			DE => &::regional_usage::DE,
			DJ => &::regional_usage::DJ,
			DK => &::regional_usage::DK,
			DM => &::regional_usage::DM,
			DO => &::regional_usage::DO,
			DZ => &::regional_usage::DZ,
			EC => &::regional_usage::EC,
			EE => &::regional_usage::EE,
			EG => &::regional_usage::EG,
			ER => &::regional_usage::ER,
			ES => &::regional_usage::ES,
			ET => &::regional_usage::ET,
			FI => &::regional_usage::FI,
			FJ => &::regional_usage::FJ,
			FK => &::regional_usage::FK,
			FM => &::regional_usage::FM,
			FO => &::regional_usage::FO,
			FR => &::regional_usage::FR,
			GA => &::regional_usage::GA,
			GB => &::regional_usage::GB,
			GD => &::regional_usage::GD,
			GE => &::regional_usage::GE,
			GF => &::regional_usage::GF,
			GG => &::regional_usage::GG,
			GH => &::regional_usage::GH,
			GI => &::regional_usage::GI,
			GL => &::regional_usage::GL,
			GM => &::regional_usage::GM,
			GN => &::regional_usage::GN,
			GP => &::regional_usage::GP,
			GQ => &::regional_usage::GQ,
			GR => &::regional_usage::GR,
			GT => &::regional_usage::GT,
			GU => &::regional_usage::GU,
			GW => &::regional_usage::GW,
			GY => &::regional_usage::GY,
			HK => &::regional_usage::HK,
			HN => &::regional_usage::HN,
			HR => &::regional_usage::HR,
			HT => &::regional_usage::HT,
			HU => &::regional_usage::HU,
			ID => &::regional_usage::ID,
			IE => &::regional_usage::IE,
			IL => &::regional_usage::IL,
			IM => &::regional_usage::IM,
			IN => &::regional_usage::IN,
			IQ => &::regional_usage::IQ,
			IR => &::regional_usage::IR,
			IS => &::regional_usage::IS,
			IT => &::regional_usage::IT,
			JE => &::regional_usage::JE,
			JM => &::regional_usage::JM,
			JO => &::regional_usage::JO,
			JP => &::regional_usage::JP,
			KE => &::regional_usage::KE,
			KG => &::regional_usage::KG,
			KH => &::regional_usage::KH,
			KI => &::regional_usage::KI,
			KM => &::regional_usage::KM,
			KN => &::regional_usage::KN,
			KP => &::regional_usage::KP,
			KR => &::regional_usage::KR,
			KW => &::regional_usage::KW,
			KY => &::regional_usage::KY,
			KZ => &::regional_usage::KZ,
			LA => &::regional_usage::LA,
			LB => &::regional_usage::LB,
			LC => &::regional_usage::LC,
			LI => &::regional_usage::LI,
			LK => &::regional_usage::LK,
			LR => &::regional_usage::LR,
			LS => &::regional_usage::LS,
			LT => &::regional_usage::LT,
			LU => &::regional_usage::LU,
			LV => &::regional_usage::LV,
			LY => &::regional_usage::LY,
			MA => &::regional_usage::MA,
			MC => &::regional_usage::MC,
			MD => &::regional_usage::MD,
			ME => &::regional_usage::ME,
			MG => &::regional_usage::MG,
			MH => &::regional_usage::MH,
			MK => &::regional_usage::MK,
			ML => &::regional_usage::ML,
			MM => &::regional_usage::MM,
			MN => &::regional_usage::MN,
			MO => &::regional_usage::MO,
			MP => &::regional_usage::MP,
			MQ => &::regional_usage::MQ,
			MR => &::regional_usage::MR,
			MS => &::regional_usage::MS,
			MT => &::regional_usage::MT,
			MU => &::regional_usage::MU,
			MV => &::regional_usage::MV,
			MW => &::regional_usage::MW,
			MX => &::regional_usage::MX,
			MY => &::regional_usage::MY,
			MZ => &::regional_usage::MZ,
			NA => &::regional_usage::NA,
			NC => &::regional_usage::NC,
			NE => &::regional_usage::NE,
			NF => &::regional_usage::NF,
			NG => &::regional_usage::NG,
			NI => &::regional_usage::NI,
			NL => &::regional_usage::NL,
			NO => &::regional_usage::NO,
			NP => &::regional_usage::NP,
			NR => &::regional_usage::NR,
			NU => &::regional_usage::NU,
			NZ => &::regional_usage::NZ,
			OM => &::regional_usage::OM,
			PA => &::regional_usage::PA,
			PE => &::regional_usage::PE,
			PF => &::regional_usage::PF,
			PG => &::regional_usage::PG,
			PH => &::regional_usage::PH,
			PK => &::regional_usage::PK,
			PL => &::regional_usage::PL,
			PM => &::regional_usage::PM,
			PN => &::regional_usage::PN,
			PR => &::regional_usage::PR,
			PS => &::regional_usage::PS,
			PT => &::regional_usage::PT,
			PW => &::regional_usage::PW,
			PY => &::regional_usage::PY,
			QA => &::regional_usage::QA,
			RE => &::regional_usage::RE,
			RO => &::regional_usage::RO,
			RS => &::regional_usage::RS,
			RU => &::regional_usage::RU,
			RW => &::regional_usage::RW,
			SA => &::regional_usage::SA,
			SB => &::regional_usage::SB,
			SC => &::regional_usage::SC,
			SD => &::regional_usage::SD,
			SE => &::regional_usage::SE,
			SG => &::regional_usage::SG,
			SH => &::regional_usage::SH,
			SI => &::regional_usage::SI,
			SK => &::regional_usage::SK,
			SL => &::regional_usage::SL,
			SM => &::regional_usage::SM,
			SN => &::regional_usage::SN,
			SO => &::regional_usage::SO,
			SR => &::regional_usage::SR,
			ST => &::regional_usage::ST,
			SV => &::regional_usage::SV,
			SY => &::regional_usage::SY,
			SZ => &::regional_usage::SZ,
			TC => &::regional_usage::TC,
			TD => &::regional_usage::TD,
			TG => &::regional_usage::TG,
			TH => &::regional_usage::TH,
			TJ => &::regional_usage::TJ,
			TK => &::regional_usage::TK,
			TL => &::regional_usage::TL,
			TM => &::regional_usage::TM,
			TN => &::regional_usage::TN,
			TO => &::regional_usage::TO,
			TR => &::regional_usage::TR,
			TT => &::regional_usage::TT,
			TV => &::regional_usage::TV,
			TW => &::regional_usage::TW,
			TZ => &::regional_usage::TZ,
			UA => &::regional_usage::UA,
			UG => &::regional_usage::UG,
			US => &::regional_usage::US,
			UY => &::regional_usage::UY,
			UZ => &::regional_usage::UZ,
			VA => &::regional_usage::VA,
			VC => &::regional_usage::VC,
			VE => &::regional_usage::VE,
			VG => &::regional_usage::VG,
			VI => &::regional_usage::VI,
			VN => &::regional_usage::VN,
			VU => &::regional_usage::VU,
			WF => &::regional_usage::WF,
			WS => &::regional_usage::WS,
			YE => &::regional_usage::YE,
			YT => &::regional_usage::YT,
			ZA => &::regional_usage::ZA,
			ZM => &::regional_usage::ZM,
			ZW => &::regional_usage::ZW,
		}
	}
	
	/// Returns a string matching the caniuse.com database's ISO-like code.
	#[inline(always)]
	pub fn can_i_use_iso_like_code(&self) -> &'static str
	{
		use self::RegionalUsages::*;
		
		match *self
		{
			WorldWide => "alt-ww",
			
			Africa => "alt-af",
			Antarctica => "alt-an",
			Asia => "alt-as",
			Europe => "alt-eu",
			NorthAmerica => "alt-na",
			Oceania => "alt-oc",
			SouthAmerica => "alt-sa",
			
			AD => "AD",
			AE => "AE",
			AF => "AF",
			AG => "AG",
			AI => "AI",
			AL => "AL",
			AM => "AM",
			AN => "AN",
			AO => "AO",
			AR => "AR",
			AS => "AS",
			AT => "AT",
			AU => "AU",
			AW => "AW",
			AX => "AX",
			AZ => "AZ",
			BA => "BA",
			BB => "BB",
			BD => "BD",
			BE => "BE",
			BF => "BF",
			BG => "BG",
			BH => "BH",
			BI => "BI",
			BJ => "BJ",
			BM => "BM",
			BN => "BN",
			BO => "BO",
			BR => "BR",
			BS => "BS",
			BT => "BT",
			BW => "BW",
			BY => "BY",
			BZ => "BZ",
			CA => "CA",
			CD => "CD",
			CF => "CF",
			CG => "CG",
			CH => "CH",
			CI => "CI",
			CK => "CK",
			CL => "CL",
			CM => "CM",
			CN => "CN",
			CO => "CO",
			CR => "CR",
			CU => "CU",
			CV => "CV",
			CX => "CX",
			CY => "CY",
			CZ => "CZ",
			DE => "DE",
			DJ => "DJ",
			DK => "DK",
			DM => "DM",
			DO => "DO",
			DZ => "DZ",
			EC => "EC",
			EE => "EE",
			EG => "EG",
			ER => "ER",
			ES => "ES",
			ET => "ET",
			FI => "FI",
			FJ => "FJ",
			FK => "FK",
			FM => "FM",
			FO => "FO",
			FR => "FR",
			GA => "GA",
			GB => "GB",
			GD => "GD",
			GE => "GE",
			GF => "GF",
			GG => "GG",
			GH => "GH",
			GI => "GI",
			GL => "GL",
			GM => "GM",
			GN => "GN",
			GP => "GP",
			GQ => "GQ",
			GR => "GR",
			GT => "GT",
			GU => "GU",
			GW => "GW",
			GY => "GY",
			HK => "HK",
			HN => "HN",
			HR => "HR",
			HT => "HT",
			HU => "HU",
			ID => "ID",
			IE => "IE",
			IL => "IL",
			IM => "IM",
			IN => "IN",
			IQ => "IQ",
			IR => "IR",
			IS => "IS",
			IT => "IT",
			JE => "JE",
			JM => "JM",
			JO => "JO",
			JP => "JP",
			KE => "KE",
			KG => "KG",
			KH => "KH",
			KI => "KI",
			KM => "KM",
			KN => "KN",
			KP => "KP",
			KR => "KR",
			KW => "KW",
			KY => "KY",
			KZ => "KZ",
			LA => "LA",
			LB => "LB",
			LC => "LC",
			LI => "LI",
			LK => "LK",
			LR => "LR",
			LS => "LS",
			LT => "LT",
			LU => "LU",
			LV => "LV",
			LY => "LY",
			MA => "MA",
			MC => "MC",
			MD => "MD",
			ME => "ME",
			MG => "MG",
			MH => "MH",
			MK => "MK",
			ML => "ML",
			MM => "MM",
			MN => "MN",
			MO => "MO",
			MP => "MP",
			MQ => "MQ",
			MR => "MR",
			MS => "MS",
			MT => "MT",
			MU => "MU",
			MV => "MV",
			MW => "MW",
			MX => "MX",
			MY => "MY",
			MZ => "MZ",
			NA => "NA",
			NC => "NC",
			NE => "NE",
			NF => "NF",
			NG => "NG",
			NI => "NI",
			NL => "NL",
			NO => "NO",
			NP => "NP",
			NR => "NR",
			NU => "NU",
			NZ => "NZ",
			OM => "OM",
			PA => "PA",
			PE => "PE",
			PF => "PF",
			PG => "PG",
			PH => "PH",
			PK => "PK",
			PL => "PL",
			PM => "PM",
			PN => "PN",
			PR => "PR",
			PS => "PS",
			PT => "PT",
			PW => "PW",
			PY => "PY",
			QA => "QA",
			RE => "RE",
			RO => "RO",
			RS => "RS",
			RU => "RU",
			RW => "RW",
			SA => "SA",
			SB => "SB",
			SC => "SC",
			SD => "SD",
			SE => "SE",
			SG => "SG",
			SH => "SH",
			SI => "SI",
			SK => "SK",
			SL => "SL",
			SM => "SM",
			SN => "SN",
			SO => "SO",
			SR => "SR",
			ST => "ST",
			SV => "SV",
			SY => "SY",
			SZ => "SZ",
			TC => "TC",
			TD => "TD",
			TG => "TG",
			TH => "TH",
			TJ => "TJ",
			TK => "TK",
			TL => "TL",
			TM => "TM",
			TN => "TN",
			TO => "TO",
			TR => "TR",
			TT => "TT",
			TV => "TV",
			TW => "TW",
			TZ => "TZ",
			UA => "UA",
			UG => "UG",
			US => "US",
			UY => "UY",
			UZ => "UZ",
			VA => "VA",
			VC => "VC",
			VE => "VE",
			VG => "VG",
			VI => "VI",
			VN => "VN",
			VU => "VU",
			WF => "WF",
			WS => "WS",
			YE => "YE",
			YT => "YT",
			ZA => "ZA",
			ZM => "ZM",
			ZW => "ZW",
		}
	}
	
	/// Returns a string matching the caniuse.com database's JSON file name.
	#[inline(always)]
	pub fn json_file_name(&self) -> &'static str
	{
		use self::RegionalUsages::*;
		
		match *self
		{
			WorldWide => "alt-ww.json",
			
			Africa => "alt-af.json",
			Antarctica => "alt-an.json",
			Asia => "alt-as.json",
			Europe => "alt-eu.json",
			NorthAmerica => "alt-na.json",
			Oceania => "alt-oc.json",
			SouthAmerica => "alt-sa.json",
			
			AD => "AD.json",
			AE => "AE.json",
			AF => "AF.json",
			AG => "AG.json",
			AI => "AI.json",
			AL => "AL.json",
			AM => "AM.json",
			AN => "AN.json",
			AO => "AO.json",
			AR => "AR.json",
			AS => "AS.json",
			AT => "AT.json",
			AU => "AU.json",
			AW => "AW.json",
			AX => "AX.json",
			AZ => "AZ.json",
			BA => "BA.json",
			BB => "BB.json",
			BD => "BD.json",
			BE => "BE.json",
			BF => "BF.json",
			BG => "BG.json",
			BH => "BH.json",
			BI => "BI.json",
			BJ => "BJ.json",
			BM => "BM.json",
			BN => "BN.json",
			BO => "BO.json",
			BR => "BR.json",
			BS => "BS.json",
			BT => "BT.json",
			BW => "BW.json",
			BY => "BY.json",
			BZ => "BZ.json",
			CA => "CA.json",
			CD => "CD.json",
			CF => "CF.json",
			CG => "CG.json",
			CH => "CH.json",
			CI => "CI.json",
			CK => "CK.json",
			CL => "CL.json",
			CM => "CM.json",
			CN => "CN.json",
			CO => "CO.json",
			CR => "CR.json",
			CU => "CU.json",
			CV => "CV.json",
			CX => "CX.json",
			CY => "CY.json",
			CZ => "CZ.json",
			DE => "DE.json",
			DJ => "DJ.json",
			DK => "DK.json",
			DM => "DM.json",
			DO => "DO.json",
			DZ => "DZ.json",
			EC => "EC.json",
			EE => "EE.json",
			EG => "EG.json",
			ER => "ER.json",
			ES => "ES.json",
			ET => "ET.json",
			FI => "FI.json",
			FJ => "FJ.json",
			FK => "FK.json",
			FM => "FM.json",
			FO => "FO.json",
			FR => "FR.json",
			GA => "GA.json",
			GB => "GB.json",
			GD => "GD.json",
			GE => "GE.json",
			GF => "GF.json",
			GG => "GG.json",
			GH => "GH.json",
			GI => "GI.json",
			GL => "GL.json",
			GM => "GM.json",
			GN => "GN.json",
			GP => "GP.json",
			GQ => "GQ.json",
			GR => "GR.json",
			GT => "GT.json",
			GU => "GU.json",
			GW => "GW.json",
			GY => "GY.json",
			HK => "HK.json",
			HN => "HN.json",
			HR => "HR.json",
			HT => "HT.json",
			HU => "HU.json",
			ID => "ID.json",
			IE => "IE.json",
			IL => "IL.json",
			IM => "IM.json",
			IN => "IN.json",
			IQ => "IQ.json",
			IR => "IR.json",
			IS => "IS.json",
			IT => "IT.json",
			JE => "JE.json",
			JM => "JM.json",
			JO => "JO.json",
			JP => "JP.json",
			KE => "KE.json",
			KG => "KG.json",
			KH => "KH.json",
			KI => "KI.json",
			KM => "KM.json",
			KN => "KN.json",
			KP => "KP.json",
			KR => "KR.json",
			KW => "KW.json",
			KY => "KY.json",
			KZ => "KZ.json",
			LA => "LA.json",
			LB => "LB.json",
			LC => "LC.json",
			LI => "LI.json",
			LK => "LK.json",
			LR => "LR.json",
			LS => "LS.json",
			LT => "LT.json",
			LU => "LU.json",
			LV => "LV.json",
			LY => "LY.json",
			MA => "MA.json",
			MC => "MC.json",
			MD => "MD.json",
			ME => "ME.json",
			MG => "MG.json",
			MH => "MH.json",
			MK => "MK.json",
			ML => "ML.json",
			MM => "MM.json",
			MN => "MN.json",
			MO => "MO.json",
			MP => "MP.json",
			MQ => "MQ.json",
			MR => "MR.json",
			MS => "MS.json",
			MT => "MT.json",
			MU => "MU.json",
			MV => "MV.json",
			MW => "MW.json",
			MX => "MX.json",
			MY => "MY.json",
			MZ => "MZ.json",
			NA => "NA.json",
			NC => "NC.json",
			NE => "NE.json",
			NF => "NF.json",
			NG => "NG.json",
			NI => "NI.json",
			NL => "NL.json",
			NO => "NO.json",
			NP => "NP.json",
			NR => "NR.json",
			NU => "NU.json",
			NZ => "NZ.json",
			OM => "OM.json",
			PA => "PA.json",
			PE => "PE.json",
			PF => "PF.json",
			PG => "PG.json",
			PH => "PH.json",
			PK => "PK.json",
			PL => "PL.json",
			PM => "PM.json",
			PN => "PN.json",
			PR => "PR.json",
			PS => "PS.json",
			PT => "PT.json",
			PW => "PW.json",
			PY => "PY.json",
			QA => "QA.json",
			RE => "RE.json",
			RO => "RO.json",
			RS => "RS.json",
			RU => "RU.json",
			RW => "RW.json",
			SA => "SA.json",
			SB => "SB.json",
			SC => "SC.json",
			SD => "SD.json",
			SE => "SE.json",
			SG => "SG.json",
			SH => "SH.json",
			SI => "SI.json",
			SK => "SK.json",
			SL => "SL.json",
			SM => "SM.json",
			SN => "SN.json",
			SO => "SO.json",
			SR => "SR.json",
			ST => "ST.json",
			SV => "SV.json",
			SY => "SY.json",
			SZ => "SZ.json",
			TC => "TC.json",
			TD => "TD.json",
			TG => "TG.json",
			TH => "TH.json",
			TJ => "TJ.json",
			TK => "TK.json",
			TL => "TL.json",
			TM => "TM.json",
			TN => "TN.json",
			TO => "TO.json",
			TR => "TR.json",
			TT => "TT.json",
			TV => "TV.json",
			TW => "TW.json",
			TZ => "TZ.json",
			UA => "UA.json",
			UG => "UG.json",
			US => "US.json",
			UY => "UY.json",
			UZ => "UZ.json",
			VA => "VA.json",
			VC => "VC.json",
			VE => "VE.json",
			VG => "VG.json",
			VI => "VI.json",
			VN => "VN.json",
			VU => "VU.json",
			WF => "WF.json",
			WS => "WS.json",
			YE => "YE.json",
			YT => "YT.json",
			ZA => "ZA.json",
			ZM => "ZM.json",
			ZW => "ZW.json",
		}
	}
}
